test

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -34,6 +34,7 @@ jobs:
           echo "COVERAGE_RESULT=$COVERAGE_RESULT" >> $GITHUB_ENV
 
       - name: Stop the application
+        if: always()
         run: kill $(cat app_pid.txt) || echo "App already stopped"
 
       - name: Store coverage report
@@ -55,8 +56,11 @@ jobs:
           TEST_STATUS="Tests completed successfully"
           ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/image.png?ex=672e058a&is=672cb40a&hm=2522f789e2bb9f856f9b989ff7a550f1f8499b4e2695805113f672db3cbcfdc6&=&format=jpeg"  # Default icon for success
 
-          # Use the value saved in the previous step to determine test result
-          if [ "${{ env.COVERAGE_RESULT }}" -lt 90 ]; then
+          # Check if tests passed or failed based on coverage result
+          if [[ $? -ne 0 ]]; then
+            TEST_STATUS="Tests failed\n[Zie test run](${PR_URL}/checks)"
+            ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/fail-icon.png"  # Icon for failure
+          elif [ "${{ env.COVERAGE_RESULT }}" -lt 90 ]; then
             TEST_STATUS="Tests failed (coverage < 90%)"
             ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/fail-icon.png"  # Icon for failure
           fi
