test

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -9,7 +9,6 @@
 #     runs-on: self-hosted
 #     steps:
 #       - uses: actions/checkout@v4
-
 #       - name: Install dependencies
 #         run: |
 #           python3 -m pip install --upgrade pip
@@ -18,24 +17,18 @@
 
 #       - name: Start the application in the background
 #         run: |
-#           python3 app/main.py > app.log 2>&1 & 
+#           python3 app/main.py > app.log 2>&1 &
 #           echo $! > app_pid.txt
 #           sleep 1
 
 #       - name: Test with pytest
 #         run: coverage run -m pytest
-#         continue-on-error: true
 
 #       - name: Run code coverage
 #         run: |
 #           coverage report -m --rcfile=.coveragerc --format=markdown >> $GITHUB_STEP_SUMMARY
-#           # Save coverage result to a variable for later use
-#           COVERAGE_RESULT=$(coverage report -m | tail -n 1 | awk '{print $NF}')
-#           echo "Coverage Result: $COVERAGE_RESULT" # Log for debugging purposes
-#           echo "COVERAGE_RESULT=$COVERAGE_RESULT" >> $GITHUB_ENV
 
 #       - name: Stop the application
-#         if: always()
 #         run: kill $(cat app_pid.txt) || echo "App already stopped"
 
 #       - name: Store coverage report
@@ -57,15 +50,6 @@
 #           TEST_STATUS="Tests completed successfully"
 #           ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/image.png?ex=672e058a&is=672cb40a&hm=2522f789e2bb9f856f9b989ff7a550f1f8499b4e2695805113f672db3cbcfdc6&=&format=jpeg"  # Default icon for success
 
-#           # Check if tests passed or failed based on coverage result
-#           if [[ $? -ne 0 ]]; then
-#             TEST_STATUS="Tests failed\n[Zie test run](${PR_URL}/checks)"
-#             ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/fail-icon.png"  # Icon for failure
-#           elif [ "${{ env.COVERAGE_RESULT }}" -lt 90 ]; then
-#             TEST_STATUS="Tests failed (coverage < 90%)"
-#             ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/fail-icon.png"  # Icon for failure
-#           fi
-
 #           MESSAGE="_____________________________________________________________\n**Pull Request:** [${PR_TITLE}](${PR_URL})\n**Author:** ${PR_AUTHOR}\n**Test Status:** ${TEST_STATUS}"
 
 #           # Send the message to Discord with the appropriate icon
@@ -73,6 +57,7 @@
 #             "content": "'"${MESSAGE}"'",
 #             "avatar_url": "'"${ICON_URL}"'"
 #           }' $DISCORD_WEBHOOK
+
 
 name: Tests run
 
@@ -85,7 +70,6 @@ jobs:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
-
       - name: Install dependencies
         run: |
           python3 -m pip install --upgrade pip
@@ -94,33 +78,21 @@ jobs:
 
       - name: Start the application in the background
         run: |
-          python3 app/main.py > app.log 2>&1 & 
+          python3 app/main.py > app.log 2>&1 &
           echo $! > app_pid.txt
           sleep 1
 
       - name: Test with pytest
         id: pytest
         run: |
-          # Run the tests and capture the output and exit code
-          pytest_output=$(coverage run -m pytest)
-          pytest_exit_code=$?
-          echo "pytest_exit_code=$pytest_exit_code" >> $GITHUB_ENV
-          echo "pytest_output=$pytest_output" >> $GITHUB_ENV
-          # Log the output and exit code for debugging
-          echo "Test results captured, continuing..."
-          echo "pytest_exit_code=$pytest_exit_code"
-          echo "pytest_output=$pytest_output"
+          coverage run -m pytest
+          echo "::set-output name=status::$(if [ $? -eq 0 ]; then echo 'success'; else echo 'failure'; fi)"
 
       - name: Run code coverage
         run: |
           coverage report -m --rcfile=.coveragerc --format=markdown >> $GITHUB_STEP_SUMMARY
-          # Save coverage result to a variable for later use
-          COVERAGE_RESULT=$(coverage report -m | tail -n 1 | awk '{print $NF}')
-          echo "Coverage Result: $COVERAGE_RESULT" # Log for debugging purposes
-          echo "COVERAGE_RESULT=$COVERAGE_RESULT" >> $GITHUB_ENV
 
       - name: Stop the application
-        if: always()
         run: kill $(cat app_pid.txt) || echo "App already stopped"
 
       - name: Store coverage report
@@ -139,37 +111,20 @@ jobs:
           PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
           PR_TITLE="${{ github.event.pull_request.title }}"
           PR_AUTHOR="${{ github.event.pull_request.user.login }}"
-
-          # Default status and icon
-          TEST_STATUS="Tests completed successfully"
-          ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/image.png?ex=672e058a&is=672cb40a&hm=2522f789e2bb9f856f9b989ff7a550f1f8499b4e2695805113f672db3cbcfdc6&=&format=jpeg"  # Success icon
-
-          # Capture the test results and error output
-          pytest_exit_code="${{ env.pytest_exit_code }}"
-          pytest_output="${{ env.pytest_output }}"
-          coverage_result="${{ env.COVERAGE_RESULT }}"
-
-          # Debugging: Print the exit code and output
-          echo "pytest_exit_code=$pytest_exit_code"
-          echo "pytest_output=$pytest_output"
-
-          # Check the pytest exit code to determine the status
-          if [ "$pytest_exit_code" -ne 0 ]; then
-            TEST_STATUS="Tests failed"
-            ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/fail-icon.png"  # Failure icon
-            MESSAGE="**Pull Request:** [${PR_TITLE}](${PR_URL})\n**Author:** ${PR_AUTHOR}\n**Test Status:** ${TEST_STATUS}\n**Error Message:**\n\`\`\`${pytest_output}\`\`\`"
-          elif [ "$coverage_result" -lt 90 ]; then
-            TEST_STATUS="Tests failed (coverage < 90%)"
-            ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/fail-icon.png"  # Failure icon
-            MESSAGE="**Pull Request:** [${PR_TITLE}](${PR_URL})\n**Author:** ${PR_AUTHOR}\n**Test Status:** ${TEST_STATUS}\n**Coverage Result:** ${coverage_result}%"
+          
+          # Determine test status
+          if [[ "${{ steps.pytest.outputs.status }}" == "success" ]]; then
+            TEST_STATUS="Tests completed successfully"
+            ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506426543837288/image.png?ex=672e058a&is=672cb40a&hm=2522f789e2bb9f856f9b989ff7a550f1f8499b4e2695805113f672db3cbcfdc6&=&format=jpeg"
           else
-            MESSAGE="**Pull Request:** [${PR_TITLE}](${PR_URL})\n**Author:** ${PR_AUTHOR}\n**Test Status:** ${TEST_STATUS}"
+            TEST_STATUS="Tests failed"
+            ICON_URL="https://media.discordapp.net/attachments/1280503605517877339/1280506416247409667/error-icon.png"  # Add an error icon URL for failure
           fi
 
-          # Send the message to Discord with the appropriate icon and detailed output
+          MESSAGE="_____________________________________________________________\n**Pull Request:** [${PR_TITLE}](${PR_URL})\n**Author:** ${PR_AUTHOR}\n**Test Status:** ${TEST_STATUS}"
+
+          # Send the message to Discord with the appropriate icon
           curl -X POST -H "Content-Type: application/json" -d '{
             "content": "'"${MESSAGE}"'",
             "avatar_url": "'"${ICON_URL}"'"
           }' $DISCORD_WEBHOOK
-
-
